# Sheet Headers Configuration

DOCS_EXTRACTION_HEADERS = [
    "Client ID",
    "Email From",
    "Email Subject",
    "Date of Extraction",
    "Original File Name",
    "Updated File Name",
    "Email Link",  
    "File Link",
    "Duplicates",
    "Buyer Name",
    "Seller Name",
    "Doc Number",
    "Date",
    "Month",
    "Financial Year",
    "Currency",
    "Currency Amount",
    "Gross Amount",
    "GST",
    "TDS",
    "Other Taxes",
    "Net Amount",
    "CGST",
    "SGST",
    "IGST",
    "GST %",
    "State Name",
    "HSN/SAC",
    "GSTIN",
    "PAN",
    "Sheet Destination", 
    "Drive Destination",  
    "Comments",   
    "Viable Check",
]

INFLOW_OUTFLOW_OTHERS_HEADERS = [
    "Client ID",
    "File Link",
    "Doc Number",
    "Date",
    "Month",
    "Financial Year",
    "Buyer Name",
    "Seller Name",
    "Currency",
    "Currency Amount",
    "Gross Amount",
    "GST",
    "TDS",
    "Other Taxes",
    "Net Amount",
    "CGST",
    "SGST",
    "IGST",
    "GST %",
    "State Name",
    "HSN/SAC",
    "GSTIN",
    "PAN",
    "Comments"
]
